# action.yml
name: 'MNG: Docker Clock GHA wrapper'
description: 'Greet someone and record the time docker wrapper'
inputs:
  action_greeter:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Default Greeter By Action'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  greeter:
    description: 'Greeter Name'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/moyshale/clock-action:latest'